dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
  - OpenZeppelin/openzeppelin-contracts@4.4.2

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'

dotenv: .env

wallets:
  dev_account_1: 
    address: ${D1_ADDRESS}
    private_key: ${D1_PRIVATE_KEY}

networks:
  default: development

  development:
    verify: False
    local: True
    vrf_keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    vrf_fee: 100000000000000000

  mainnet-fork-dev:
    verify: False
    local: 'fork'
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'

  rinkeby:
    verify: True
    local: False
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    vrf_keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    vrf_fee: 100000000000000000
